In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
df = pd.read_csv('carprices.csv')

In [4]:
df.sample()

Car Model  Mileage  Sell Price($)  Age(yrs)
5   Audi A5    59000          29400         5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Car Model      13 non-null     object
 1   Mileage        13 non-null     int64 
 2   Sell Price($)  13 non-null     int64 
 3   Age(yrs)       13 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 544.0+ bytes


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
dfml = df

In [8]:
dfml['n_carModel'] = le.fit_transform(dfml['Car Model'])

In [9]:
dfml

Car Model  Mileage  Sell Price($)  Age(yrs)  n_carModel
0                  BMW X5    69000          18000         6           1
1                  BMW X5    35000          34000         3           1
2                  BMW X5    57000          26100         5           1
3                  BMW X5    22500          40000         2           1
4                  BMW X5    46000          31500         4           1
5                 Audi A5    59000          29400         5           0
6                 Audi A5    52000          32000         5           0
7                 Audi A5    72000          19300         6           0
8                 Audi A5    91000          12000         8           0
9   Mercedez Benz C class    67000          22000         6           2
10  Mercedez Benz C class    83000          20000         7           2
11  Mercedez Benz C class    79000          21000         7           2
12  Mercedez Benz C class    59000          33000         5           2

In [12]:
X = dfml.drop(['Car Model','Sell Price($)'], axis='columns').values

In [13]:
X 

array([[69000,     6,     1],
       [35000,     3,     1],
       [57000,     5,     1],
       [22500,     2,     1],
       [46000,     4,     1],
       [59000,     5,     0],
       [52000,     5,     0],
       [72000,     6,     0],
       [91000,     8,     0],
       [67000,     6,     2],
       [83000,     7,     2],
       [79000,     7,     2],
       [59000,     5,     2]], dtype=int64)

In [16]:
Y = dfml['Sell Price($)'].values

In [27]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('n_carModel', OneHotEncoder(),[2])],remainder = 'passthrough')

In [28]:
X = ct.fit_transform(X)
X

array([[1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 6.90e+04,
        6.00e+00],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 3.50e+04,
        3.00e+00],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 5.70e+04,
        5.00e+00],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 2.25e+04,
        2.00e+00],
       [1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 4.60e+04,
        4.00e+00],
       [0.00e+00, 1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04,
        5.00e+00],
       [0.00e+00, 1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04,
        5.00e+00],
       [0.00e+00, 1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04,
        6.00e+00],
       [0.00e+00, 1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04,
        8.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 6.70e+04,
        6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 8.30e+04,
        7.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.00e

In [29]:
X = X[:,1:]

In [30]:
X 

array([[0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 5.90e+04, 5.00e+00]])

In [31]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()

In [32]:
LR.fit(X,Y)

LinearRegression()

In [35]:
LR.score(X,Y)

0.9417050937281083